### 유저 회원가입 테스트
POST localhost:8080/user
Content-Type: application/json

{
  "userId": "testId1",
  "password": "password",
  "nickname": "nick"
}

### 유저 회원가입 테스트 닉네임 제외
POST localhost:8080/user
Content-Type: application/json

{
  "userId": "tatata",
  "password": "asdfasdf"
}

### 본인 정보 얻기 (리다이렉트)
GET localhost:8080/user/me

### 유저 정보 수정
PATCH localhost:8080/user/me
Content-Type: application/json

{
  "nickname": "kololalalal"
}

### 유저 탈퇴
DELETE localhost:8080/user/quit

### 유저 조회
GET localhost:8080/user/testId2

### 존재하지 않는 유저 조회
GET localhost:8080/user/ThisUserIsNotExists

### 유저 아이디 존재여부 확인 (존재하는 유저일 떄)
GET localhost:8080/user/testId1/check-id

### 유저 아이디 존재여부 확인 (존재하지 않는 유저일 떄)
GET localhost:8080/user/ThisUserIsNotExists/check-id
